version: '3'
services:
  postgres:
    container_name: on_school
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: on_school